adapted to work on simple shell sh

diff --git a/telegram b/telegram
--- a/telegram
+++ b/telegram
@@ -1,8 +1,10 @@
-#!/bin/bash
+#!/bin/sh
+# https://github.com/fabianonline/telegram.sh
+# adapted to work on simple shell sh
 
-VERSION="0.3"
+VERSION="0.3.1"
 TOKEN=""
-CHATS=()
+ACHAT=""
 DEBUG=false
 DRY_RUN=false
 
@@ -24,9 +26,12 @@ HAS_JQ=false
 hash jq >/dev/null 2>&1 && HAS_JQ=true
 
 
-function help {
+help() {
 	version
-	echo "Usage: $0 [options] [message]"
+	echo "Usage: $0 [options] [-m message]"
+	echo
+	echo "    -m <message>     Text message to send."
+	echo "                     Message can be '-', in that case STDIN will be used."
 	echo
 	echo "OPTIONS are:"
 	echo "    -t <TOKEN>       Telegram bot token to use. See ENVIRONMENT for more information."
@@ -51,8 +56,6 @@ function help {
 	echo "    -j               Pretend you don't have JQ installed."
 	echo "    -n               Dry-run - don't send messages, only print them on screen."
 	echo
-	echo "Message can be '-', in that case STDIN will be used."
-	echo
 	echo "ENVIRONMENT"
 	echo "    TOKEN and CHAT_ID are required. You can set them in four different ways:"
 	echo "      1) globally in /etc/telegram.sh.conf"
@@ -65,12 +68,12 @@ function help {
 	exit
 }
 
-function version {
+version() {
 	echo "telegram.sh version $VERSION"
 	echo "by Fabian Schlenz"
 }
 
-function list_chats {
+list_chats() {
 	log "$URL$TOKEN"
 	response=`curl $CURL_OPTIONS $URL$TOKEN/getUpdates`
 	log "$response"
@@ -80,11 +83,11 @@ function list_chats {
 		echo "If there are no chats or the chat you are looking for isn't there, run this command again"
 		echo "after sending a message to your bot via telegram."
 		echo
-		jq -r '.result | .[].message.chat | "\(.id|tostring) - \(.first_name) \(.last_name) (@\(.username))"' 2>/dev/null <<< "$response" || {
-			echo "Could not parse reponse from Telegram."
-			echo "Response was: $response"
-			exit 1
-		}
+		#jq -r '.result | .[].message.chat | "\(.id|tostring) - \(.first_name) \(.last_name) (@\(.username))"' 2>/dev/null <<< "$response" || {
+			#echo "Could not parse reponse from Telegram."
+			#echo "Response was: $response"
+			#exit 1
+		#}
 	else
 		echo "You don't have jq installed. I'm afraid I can't parse the JSON from telegram without it."
 		echo "So I'll have you do it. ;-)"
@@ -100,7 +103,7 @@ function list_chats {
 	fi
 }
 
-function receive_file {
+receive_file() {
 	if [ "$HAS_JQ" = false ]; then
 		echo "You need to have jq installed in order to be able to download files."
 		exit 1
@@ -117,18 +120,18 @@ function receive_file {
 	#       "chat":{"id":15773,"first_name":"Fabian","last_name":"Schlenz","username":"fabianonline","type":"private"},
 	#       "date":1526564127,
 	#       "document":{"file_name":"desktop.ini","file_id":"BQAav-HkXugI","file_size":282}}}]}
-	file_id=`jq -r '.result[-1].message.document.file_id' <<< "$result"`
+	#file_id=`jq -r '.result[-1].message.document.file_id' <<< "$result"`
 	log "file_id: $file_id"
 	if [ "$file_id" == "null" ]; then
 		echo "Last message received apparently didn't contain a file. Aborting."
 		exit 1
 	fi
-	file_name=`jq -r '.result[-1].message.document.file_name' <<< "$result"`
+	#file_name=`jq -r '.result[-1].message.document.file_name' <<< "$result"`
 	log "file_name: $file_name"
 	result=`curl $CURL_OPTIONS $URL$TOKEN/getFile?file_id=$file_id`
 	log $result
 	# {"ok":true,"result":{"file_id":"BQAav-HkXugI","file_size":282,"file_path":"documents/file_271.ini"}}
-	path=`jq -r '.result.file_path' <<< "$result"`
+	#path=`jq -r '.result.file_path' <<< "$result"`
 	log "path: $path"
 	if [ "$path" == "null" ]; then
 		echo "Could not parse telegram's response to getFile. Aborting."
@@ -144,24 +147,24 @@ function receive_file {
 	echo "File downloaded as $file_name"
 }
 
-function log {
+log() {
 	[ "$DEBUG" = true ] && echo "DEBUG: $1"
 }
 
-function check_file {
+check_file() {
 	if [ ! -e "$1" ]; then
 		echo "The file $1 does not exist."
 		exit 1
 	fi
 
 	size=$(stat -c%s "$1")
-	if (( size > 52428800 )); then
+	if [ "$size" -gt 52428800 ]; then
 		echo "File $1 is breaking the file size limit imposed on Telegram bots (currently 50MB)."
 		exit 1
 	fi
 }
 
-function escapeMarkdown {
+escapeMarkdown() {
 	res="${1//\*/∗}"
 	res="${res//_/＿}"
 	res="${res//\`/‵}"
@@ -169,70 +172,78 @@ function escapeMarkdown {
 	echo "$res"
 }
 
-while getopts "t:c:i:f:MHCrhlvjnRDNT:" opt; do
-	case $opt in
-		t)
-			TOKEN="$OPTARG"
+ARGNUM="$#"
+while [ "$#" -gt 0 ]; do
+# "t:c:i:f:MHCrhlvjnRDNT:"
+	case $1 in
+		-t)
+			TOKEN="$2"
 			;;
-		c)
-			CHATS+=("$OPTARG")
+		-c)
+			ACHAT="$2"
 			;;
-		i)
-			IMAGE_FILE="$OPTARG"
+		-m)
+			TEXT="$2"
+			if [ "$TEXT" = "-" ]; then shift ; fi
 			;;
-		f)
-			DOCUMENT_FILE="$OPTARG"
+		-i)
+			IMAGE_FILE="$2"
 			;;
-		M)
+		-f)
+			DOCUMENT_FILE="$2"
+			;;
+		-M)
 			PARSE_MODE="Markdown"
 			;;
-		H)
+		-H)
 			PARSE_MODE="HTML"
 			;;
-		C)
+		-C)
 			PARSE_MODE="Markdown"
 			CODE_MODE=1
 			;;
-		r)
+		-r)
 			PARSE_MODE="Markdown"
 			CRON_MODE=1
 			;;
-		l)
+		-l)
 			ACTION="list_chats"
 			;;
-		v)
+		-v)
 			DEBUG=true
 			;;
-		j)
+		-j)
 			HAS_JQ=false
 			;;
-		n)
+		-n)
 			DRY_RUN=true
 			;;
-		R)
+		-R)
 			ACTION="receive_file"
 			;;
-		D)
+		-D)
 			DISABLE_WEB_PAGE_PREVIEW=true
 			;;
-		N)
+		-N)
 			DISABLE_NOTIFICATION=true
 			;;
-		T)
-			TITLE="$OPTARG"
+		-T)
+			TITLE="$2"
 			;;
-		?|h)
+		-?|-h)
 			help
 			;;
-		:)
-			echo "Option -$OPTARG needs an argument."
+		--)
+			break
+			;;
+		-*)
+			echo "Invalid option '$1', use '-h' to help" >&2
 			exit 1
 			;;
-		\?)
-			echo "Invalid option -$OPTARG"
-			exit 1
-			;;
-	esac
+		# an option argument, continue
+		*)	;;
+		esac
+		shift
 done
 
 if [ "$CRON_MODE" -eq 1 ] && [ "$CODE_MODE" -eq 1 ]; then
@@ -241,26 +252,27 @@ if [ "$CRON_MODE" -eq 1 ] && [ "$CODE_MODE" -eq 1 ]; then
 fi
 
 log "TOKEN is now $TOKEN"
-log "CHATS is now ${CHATS[*]}"
+log "ACHAT is now $ACHAT"
 
 [ -z "$TOKEN" ] && TOKEN=$TELEGRAM_TOKEN
-[ ${#CHATS[@]} -eq 0 ] && CHATS=($TELEGRAM_CHAT)
+[ -z "$ACHAT" ] && ACHAT=$TELEGRAM_CHAT
 
 log "TOKEN is now $TOKEN"
-log "CHATS is now ${CHATS[*]}"
+log "ACHAT is now $ACHAT"
 
 log "Importing config file(s)..."
 
-[ -r /etc/telegram.sh.conf ] && source /etc/telegram.sh.conf
-[ -r ~/.telegram.sh ] && source ~/.telegram.sh
+[ -r /etc/telegram.sh.conf ] && . /etc/telegram.sh.conf
+[ -r ~/.telegram.sh ] && . ~/.telegram.sh
+[ -r ./.telegram.sh ] && . ./.telegram.sh
 
 [ -z "$TOKEN" ] && TOKEN=$TELEGRAM_TOKEN
-[ ${#CHATS[@]} -eq 0 ] && CHATS=($TELEGRAM_CHAT)
+[ -z "$ACHAT" ] && ACHAT=$TELEGRAM_CHAT
 [ -n "$TELEGRAM_DISABLE_WEB_PAGE_PREVIEW" ] && DISABLE_WEB_PAGE_PREVIEW="$TELEGRAM_DISABLE_WEB_PAGE_PREVIEW"
 [ -n "$TELEGRAM_DISABLE_NOTIFICATION" ] && DISABLE_NOTIFICATION="$TELEGRAM_DISABLE_NOTIFICATION"
 
 log "TOKEN is now $TOKEN"
-log "CHATS is now ${CHATS[*]}"
+log "ACHAT is now $ACHAT"
 log "DISABLE_WEB_PAGE_PREVIEW is now $DISABLE_WEB_PAGE_PREVIEW"
 log "DISABLE_NOTIFICATION is now $DISABLE_NOTIFICATION"
 
@@ -269,8 +281,8 @@ if [ -z "$TOKEN" ]; then
 	exit 1
 fi
 
-if [ ${#CHATS[@]} -eq 0 ] && [ -z "$ACTION" ]; then
-	echo "No chat(s) given."
+if [ -z "$ACHAT" ] && [ -z "$ACTION" ]; then
+	echo "No chat given."
 	exit 1
 fi
 
@@ -284,8 +296,6 @@ if [ "$ACTION" = "receive_file" ]; then
 	exit 0
 fi
 
-shift $((OPTIND - 1))
-TEXT="$1"
 log "Text: $TEXT"
 
 [ "$TEXT" = "-" ] && TEXT=$(</dev/stdin)
@@ -298,11 +308,11 @@ fi
 
 if [ $CRON_MODE -eq 1 ]; then
 	ONLY_COMMANDS=1
-	while read line; do
+	echo "$TEXT" | while read line; do
 		if [ "${line:0:2}" = "+ " ]; then
 			ONLY_COMMANDS=0
 		fi
-	done <<< "$TEXT"
+	done
 
 	if [ "$ONLY_COMMANDS" -eq 1 ]; then
 		exit 0
@@ -335,12 +345,12 @@ fi
 log "Text: $TEXT"
 
 if [ -n "$TITLE" ]; then
-	if [ "$PARSE_MODE" == "HTML" ]; then
-		TEXT="<b>$TITLE</b>"$'\n\n'"$TEXT"
-	elif [ "$PARSE_MODE" == "Markdown" ]; then
-		TEXT="*$TITLE*"$'\n\n'"$TEXT"
+	if [ "$PARSE_MODE" = "HTML" ]; then
+		TEXT="<b>$TITLE</b>"$'\n'"$TEXT"
+	elif [ "$PARSE_MODE" = "Markdown" ]; then
+		TEXT="*$TITLE*"$'\n'"$TEXT"
 	else
-		TEXT="$TITLE"$'\n\n'"$TEXT"
+		TEXT="$TITLE"$'\n'"$TEXT"
 	fi
 fi
 
@@ -374,7 +384,7 @@ fi
 
 [ "$DISABLE_NOTIFICATION" = true ] && CURL_OPTIONS="$CURL_OPTIONS --form-string disable_notification=true"
 
-for id in "${CHATS[@]}"; do
+for id in "$ACHAT"; do
 	MY_CURL_OPTIONS="$CURL_OPTIONS --form-string chat_id=$id $URL$TOKEN/$METHOD"
 	if [ "$DRY_RUN" = true ]; then
 		echo "Executing: curl $MY_CURL_OPTIONS"
@@ -383,7 +393,7 @@ for id in "${CHATS[@]}"; do
 		status=0
 		response='{"ok": true}'
 	else
-		response=`curl $MY_CURL_OPTIONS <<< "$TEXT"`
+		response=`echo "$TEXT" | curl $MY_CURL_OPTIONS`
 		status=$?
 	fi
 	log "Response was: $response"
@@ -394,19 +404,22 @@ for id in "${CHATS[@]}"; do
 		exit $status
 	fi
 
-	if [ "$HAS_JQ" = true ]; then
-		if [ "`jq -r '.ok' <<< "$response"`" != "true" ]; then
-			echo "Telegram reported following error:"
-			jq -r '"\(.error_code): \(.description)"' <<< "$response"
-			echo "Quitting."
-			exit 1
-		fi
-	else
-		if [[ "$response" != '{"ok":true'* ]]; then
-			echo "Telegram reported an error:"
-			echo $response
-			echo "Quitting."
-			exit 1
-		fi
-	fi
+	#if [ "$HAS_JQ" = true ]; then
+		##if [ "`jq -r '.ok' <<< "$response"`" != "true" ]; then
+			#echo "Telegram reported following error:"
+			##jq -r '"\(.error_code): \(.description)"' <<< "$response"
+			#echo "Quitting."
+			#exit 1
+		##fi
+	#else
+		case "$response" in
+			'{"ok":true'*)
+				;;
+			*)
+				echo "Telegram reported an error:"
+				echo $response
+				echo "Quitting."
+				exit 1
+		esac
+	#fi
 done
